support for warning(s)  initial commit
PropertyTools/PropertyTools pull request #247
Opened 2020-08-26 11:53 UTC by Sainyam2003

2020-08-26 13:57 UTC, objorke requested changes
The submodule must be removed

2020-08-27 08:03 UTC, objorke requested changes
This looks good!

I have suggested a few changes to make less changes on the library, I think it would be better to put all the custom functionality into the example. It is possible that there may be more severity levels, we should not limit the `PropertyGrid` to errors and warnings only.

I created #248 for this PR.

Remember to update the change log and authors/contributors files.

2020-08-27 08:03 UTC, objorke commented on Source/Examples/PropertyGrid/PropertyGridDemo/Examples/NotifyDataErrorInfoSeverityExample.cs
> +                this.Validate("FirstName", !string.IsNullOrEmpty(this.firstName), "First Name should not be numeric.", Severity.Warning);
use IsNumeric?

2020-08-27 08:03 UTC, objorke commented on Source/Examples/PropertyGrid/PropertyGridDemo/CustomControlFactory.cs
> +                    tab.UpdateTabForValidationResults(notifyDataErrorInfoInstance);
can implement directly here (or in a private method)
```
tab.HasErrors = ...
tab.HasWarnings = ...
```

2020-08-27 08:03 UTC, objorke commented on Source/PropertyTools.Wpf/Validation/ValidationResultEx.cs
> +using System.Collections.Generic;
the coding style is to put "using" inside the namespace block

2020-08-27 08:21 UTC, objorke requested changes

2020-08-27 08:21 UTC, objorke commented on Source/Examples/PropertyGrid/PropertyGridDemo/Examples/NotifyDataErrorInfoSeverityExample.cs
> +                this.Validate("FirstName", !string.IsNullOrEmpty(this.firstName), "First Name should not be numeric.", Severity.Warning);
I don't think the Validate method supports being called two times

2020-08-28 07:09 UTC, Sainyam2003 commented on Source/PropertyTools.Wpf/Validation/ValidationResultEx.cs
> +    public class ValidationResultEx : ValidationResult
done.

2020-08-28 07:09 UTC, Sainyam2003 commented on Source/PropertyTools.Wpf/PropertyGrid/Tab.cs
> +        public void UpdateTabForValidationResults(INotifyDataErrorInfo errorInfo)
done.

2020-08-28 07:10 UTC, Sainyam2003 commented on Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
> +        public virtual ContentControl CreateErrorControl(PropertyItem pi, object instance, Tab tab)
it is because of inheriting from interface

2020-08-28 07:50 UTC, Sainyam2003 commented
I would still need your help to change Control's border color in case of warning(s), I can not find the place in code.

2020-08-28 08:01 UTC, objorke reviewed
The `PropertyGrid` control looks ok now!
I just cannot get the example to work properly, the error messages are not showing as expected and the color of the tab header is not changing.

2020-08-28 08:32 UTC, objorke commented on Source/PropertyTools.Wpf/PropertyGrid/PropertyGrid.cs
> +                    PropertyControlFactoryOptions options = new PropertyControlFactoryOptions { ValidationErrorTemplate = this.ValidationErrorTemplate };
move this code into the ´PropertyGrid.CreateErrorControl´ method?
or remove the ´PropertyGrid.CreateErrorControl´ method

2020-09-01 12:02 UTC, objorke requested changes
The example is still not working properly.
Besides from that it looks good to merge!

2020-09-01 12:11 UTC, objorke approved these changes

2020-09-01 12:13 UTC, merged